package vetsi_bere;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author THUND
 */
public class GameGraphics extends javax.swing.JPanel implements PropertyChangeListener {

    Card c = new Card(-1, null, null, "src/Cards/back.png");
    private int newGame = 0;

    /**
     * Creates new form Graphics
     */
    public GameGraphics() {
        initComponents();
    }
    
    public void newGame() {
        newGame = 1;
    }
    
    private void drawPlayer(int player, int x, int y, Graphics g) {
        if(player >= PlayerManager.getPlayers().size()) {
            return;
        }
        // Max players = 8
        // 2 rows, 4 cols
        int w = getWidth() / 4;
        int h = getHeight() / 4;
        if(newGame > 1) {
            if(PlayerManager.getPlayers().get(player).peek() != null) {
                PlayerManager.getPlayers().get(player).peek().drawCard(g, new Point(x * w, y * h), h);
            }
        }
        if(PlayerManager.getPlayers().get(player).cardsLeft() != 0) {
            c.drawCard(g, new Point(x * w + w / 2, y * h), h);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        g.setColor(Color.white);
        g.fillRect(0, 0, 1000, 1000);
        drawPlayer(5, 0, 0, g);
        drawPlayer(1, 1, 0, g);
        drawPlayer(3, 2, 0, g);
        drawPlayer(7, 3, 0, g);
        drawPlayer(6, 0, 3, g);
        drawPlayer(2, 1, 3, g);
        drawPlayer(0, 2, 3, g);
        drawPlayer(4, 3, 3, g);
        newGame++;
    }

    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        if(pce.getPropertyName().equals("drawPull")) {
            repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
