package vetsi_bere;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author THUND
 */
public class Game extends javax.swing.JFrame implements PropertyChangeListener {

    private GameManager gm = new GameManager();
    private gameOver go = new gameOver();
    
    /**
     * Creates new form Game
     */
    public Game() {
        initComponents();
        gm.setUpGame();
        gm.addPropertyChangeListener(graphics1);
        gm.addPropertyChangeListener(go);
        gm.addPropertyChangeListener(this);
        go.addPropertyChangeListener(this);
        text();
    }
    
    public void text() {
        try {
            p0.setText(PlayerManager.getPlayers().get(0).toString() + " (" + PlayerManager.getPlayers().get(0).cardsLeft() + ")");
            p1.setText(PlayerManager.getPlayers().get(1).toString() + " (" + PlayerManager.getPlayers().get(1).cardsLeft() + ")");
            p2.setText(PlayerManager.getPlayers().get(2).toString() + " (" + PlayerManager.getPlayers().get(2).cardsLeft() + ")");
            p3.setText(PlayerManager.getPlayers().get(3).toString() + " (" + PlayerManager.getPlayers().get(3).cardsLeft() + ")");
            p4.setText(PlayerManager.getPlayers().get(4).toString() + " (" + PlayerManager.getPlayers().get(4).cardsLeft() + ")");
            p5.setText(PlayerManager.getPlayers().get(5).toString() + " (" + PlayerManager.getPlayers().get(5).cardsLeft() + ")");
            p6.setText(PlayerManager.getPlayers().get(6).toString() + " (" + PlayerManager.getPlayers().get(6).cardsLeft() + ")");
            p7.setText(PlayerManager.getPlayers().get(7).toString() + " (" + PlayerManager.getPlayers().get(7).cardsLeft() + ")");
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphics1 = new vetsi_bere.GameGraphics();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        p6 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p0 = new javax.swing.JLabel();
        p4 = new javax.swing.JLabel();
        p5 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p3 = new javax.swing.JLabel();
        p7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Tahat karty");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        p6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        p7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout graphics1Layout = new javax.swing.GroupLayout(graphics1);
        graphics1.setLayout(graphics1Layout);
        graphics1Layout.setHorizontalGroup(
            graphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphics1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(graphics1Layout.createSequentialGroup()
                .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p0, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(graphics1Layout.createSequentialGroup()
                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        graphics1Layout.setVerticalGroup(
            graphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphics1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(graphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(graphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(graphics1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p0, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphics1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphics1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gm.pullCards();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vetsi_bere.GameGraphics graphics1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel p0;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel p3;
    private javax.swing.JLabel p4;
    private javax.swing.JLabel p5;
    private javax.swing.JLabel p6;
    private javax.swing.JLabel p7;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        if(pce.getPropertyName().equals("drawResult")) {
            jLabel1.setText((String) pce.getNewValue());
            text();
            repaint();
        }
        if(pce.getPropertyName().equals("gameFinish")) {
            jButton1.setEnabled(false);
        }
        if(pce.getPropertyName().equals("start")) {
            setVisible(true);
            gm.setUpGame();
            graphics1.newGame();
            graphics1.repaint();
            text();
            repaint();
            jButton1.setEnabled(true);
        }
        if(pce.getPropertyName().equals("backToMenu")) {
            this.setVisible(false);
            firePropertyChange("backToMenu", false, true);
        }
    }
}
