package kostky;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;

public class StatistikaOkno extends javax.swing.JFrame implements PropertyChangeListener {

    private final String keyword;
    private final boolean reset;
    private final boolean suma;
    private boolean freed = false;
    private final PropertyChangeSupport pcs;
    private int jednicky = 0;
    private int dvojky = 0;
    private int trojky = 0;
    private int ctyrky = 0;
    private int petky = 0;
    private int sestky = 0;
    private int sum = 0;
    public StatistikaOkno(String keyword, boolean reset, boolean suma) {
        initComponents();
        
        this.keyword = keyword;
        this.reset = reset;
        this.suma = suma;
        
        this.pcs = new PropertyChangeSupport( this );
        this.jLabel1.setText(keyword);
        this.sumaLabel.setVisible(suma);
        this.jButton1.setVisible(!reset);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jednaCounter = new javax.swing.JLabel();
        dvaCounter = new javax.swing.JLabel();
        triCounter = new javax.swing.JLabel();
        ctyriCounter = new javax.swing.JLabel();
        petCounter = new javax.swing.JLabel();
        sestCounter = new javax.swing.JLabel();
        sumaLabel = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        jButton1.setText("Resetovat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Statistika");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("3");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("4");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("5");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("6");

        jednaCounter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jednaCounter.setText("0x");

        dvaCounter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dvaCounter.setText("0x");

        triCounter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        triCounter.setText("0x");

        ctyriCounter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ctyriCounter.setText("0x");

        petCounter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        petCounter.setText("0x");

        sestCounter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sestCounter.setText("0x");

        sumaLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sumaLabel.setText("0");

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jednaCounter)
                                            .addComponent(dvaCounter)
                                            .addComponent(triCounter)
                                            .addComponent(ctyriCounter)
                                            .addComponent(petCounter)
                                            .addComponent(sestCounter))))
                                .addGap(97, 97, 97))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(sumaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jednaCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dvaCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(triCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ctyriCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(petCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sestCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sumaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.resetuj();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        this.freed = !freed;
        this.jCheckBox1.setSelected( this.freed );
        if(this.freed){
            this.pcs.firePropertyChange("free", null, this.getID());
        }else{
            this.pcs.firePropertyChange("lock", null, this.getID());
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ctyriCounter;
    private javax.swing.JLabel dvaCounter;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jednaCounter;
    private javax.swing.JLabel petCounter;
    private javax.swing.JLabel sestCounter;
    private javax.swing.JLabel sumaLabel;
    private javax.swing.JLabel triCounter;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        if ( pce.getPropertyName().equals( this.keyword ) )
        {
            if( pce.getNewValue().equals("1") ){
                this.jednicky += 1;
            }else if( pce.getNewValue().equals("2") ){
                this.dvojky += 1;
            }else if( pce.getNewValue().equals("3") ){
                this.trojky += 1;
            }else if( pce.getNewValue().equals("4") ){
                this.ctyrky += 1;
            }else if( pce.getNewValue().equals("5") ){
                this.petky += 1;
            }else if( pce.getNewValue().equals("6") ){
                this.sestky += 1;
            }
            this.sum += Integer.parseInt((String)pce.getNewValue());
            this.updateLabels();
        }

        if ( pce.getPropertyName().equals( "statistika_reset" ) && this.reset )
        {
            this.resetuj();
        }
    }
    
    private void updateLabels(){
        this.jednaCounter.setText( String.valueOf(jednicky) + "x" );
        this.dvaCounter.setText( String.valueOf(dvojky) + "x" );
        this.triCounter.setText( String.valueOf(trojky) + "x" );
        this.ctyriCounter.setText( String.valueOf(ctyrky) + "x" );
        this.petCounter.setText( String.valueOf(petky) + "x" );
        this.sestCounter.setText( String.valueOf(sestky) + "x" );
        this.sumaLabel.setText( String.valueOf(sum) );
    }
    
    private void resetuj(){
        this.jednicky = 0;
        this.dvojky = 0;
        this.trojky = 0;
        this.ctyrky = 0;
        this.petky = 0;
        this.sestky = 0;
        this.sum = 0;
        this.updateLabels();
    }
    
    public String getID(){
        return this.keyword;
    }
    
    public void pridejListener( PropertyChangeListener l )
    {
        this.pcs.addPropertyChangeListener( l );
    }

    public void odeberListener( PropertyChangeListener l )
    {
        this.pcs.removePropertyChangeListener( l );
    }
}
