package snake_machado;

import java.awt.Point;
import java.awt.event.KeyEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 *
 * @author THUND
 */
public class GameWindow extends javax.swing.JFrame implements PropertyChangeListener {

    private GameManager gm = new GameManager();
    GameOverWindow gow = new GameOverWindow();
    
    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
        
        gm.addPropertyChangeListener(boardPainter1);
        gm.addPropertyChangeListener(this);
        this.addPropertyChangeListener(gm);
        
        gm.addPropertyChangeListener(gow);
        gow.addPropertyChangeListener(this);
    }
    
    private void backToMenu() {
        setVisible(false);
        firePropertyChange("backToMenu", null, getLocation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardPainter1 = new snake_machado.BoardPainter();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        boardPainter1.setFocusable(false);

        javax.swing.GroupLayout boardPainter1Layout = new javax.swing.GroupLayout(boardPainter1);
        boardPainter1.setLayout(boardPainter1Layout);
        boardPainter1Layout.setHorizontalGroup(
            boardPainter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        boardPainter1Layout.setVerticalGroup(
            boardPainter1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setText("Zpět do menu");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boardPainter1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(boardPainter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        backToMenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_W:
            case KeyEvent.VK_UP:
                firePropertyChange("changeDir", null, Direction.NORTH);
                break;
            case KeyEvent.VK_D:
            case KeyEvent.VK_RIGHT:
                firePropertyChange("changeDir", null, Direction.WEST);
                break;
            case KeyEvent.VK_S:
            case KeyEvent.VK_DOWN:
                firePropertyChange("changeDir", null, Direction.SOUTH);
                break;
            case KeyEvent.VK_A:
            case KeyEvent.VK_LEFT:
                firePropertyChange("changeDir", null, Direction.EAST);
                break;
            default:
        }
    }//GEN-LAST:event_formKeyPressed

    @Override
    public void propertyChange(PropertyChangeEvent pce) {
        if(pce.getPropertyName().equals("newGame")) {
            jButton1.setEnabled(true);
            setLocation((Point) pce.getNewValue());
            setVisible(true);
            gm.newGame();
        }
        if(pce.getPropertyName().equals("backToMenu")) {
            backToMenu();
        }
        if(pce.getPropertyName().equals("gameOver")) {
            jButton1.setEnabled(false);
            gow.setLocation(getLocation());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private snake_machado.BoardPainter boardPainter1;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
