package tictactoe;

import java.awt.Component;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.WindowConstants;

/**
 *
 * @author THUND
 */
public class Settings extends javax.swing.JFrame {

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        fillOutCharSelect();
        setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent ce) {
                super.componentShown(ce);
                fillOutCharSelect();
                updatePlayerLabels();
                disableCorrectChars();
            }
        });
    }

    private void fillOutCharSelect() {
        p_charSelect.removeAll();

        ArrayList<String> chrs = CharacterManager.getAllSymbols();

        int margin = 12;
        int btnSize = 40;
        int cols = p_charSelect.getWidth() / btnSize;

        for (int i = 0; i < chrs.size(); i++) {
            JButton btn = new JButton(chrs.get(i));
            btn.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
            btn.setMargin(new java.awt.Insets(1, 1, 1, 1));
            btn.setBounds((i % cols) * btnSize + margin, (i / cols) * btnSize + margin, btnSize, btnSize);

            int j = i;
            btn.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent ae) {
                    int playerID = (tb_p1.isSelected()) ? 0 : 1;
                    
                    CharacterManager.setCharToPlayer(playerID, j);
                    updatePlayerLabels();
                    
                    disableCorrectChars();
                }
            });

            p_charSelect.add(btn);
        }

        // p_charSelect.setBounds(p_charSelect.getX(), p_charSelect.getY(), cols + margin * 2, (chrs.size() / cols) + margin * 2);
        p_charSelect.revalidate();
        p_charSelect.repaint();
        revalidate();
        repaint();
    }
    
    private void updatePlayerLabels() {
        l_p1Char.setText(CharacterManager.getSymbolForPlayer(0));
        l_p2Char.setText(CharacterManager.getSymbolForPlayer(1));
        repaint();
    }
    
    private void disableCorrectChars() {
        Component[] btns = p_charSelect.getComponents();
                
        ArrayList<Integer> ids = CharacterManager.getPlayerIDs();
        
        for (int i = 0; i < btns.length; i++) {
            if(ids.contains(i)) {
                // Player owns this char
                btns[i].setEnabled(false);
            } else {
                btns[i].setEnabled(true);
            }
        }
    }
    
    public Point getBoardSize() {
       return new Point(s_xSize.getValue(), s_ySize.getValue());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p_charSelect = new javax.swing.JPanel();
        b_dummy = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        p_p1 = new javax.swing.JPanel();
        tb_p1 = new javax.swing.JToggleButton();
        l_p1Char = new javax.swing.JLabel();
        p_p2 = new javax.swing.JPanel();
        tb_p2 = new javax.swing.JToggleButton();
        l_p2Char = new javax.swing.JLabel();
        p_xSize = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        s_xSize = new javax.swing.JSlider();
        p_ySize = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        s_ySize = new javax.swing.JSlider();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Výběr symbolu");

        p_charSelect.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        b_dummy.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        b_dummy.setText("#");
        b_dummy.setMargin(new java.awt.Insets(1, 1, 1, 1));

        javax.swing.GroupLayout p_charSelectLayout = new javax.swing.GroupLayout(p_charSelect);
        p_charSelect.setLayout(p_charSelectLayout);
        p_charSelectLayout.setHorizontalGroup(
            p_charSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_charSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_dummy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_charSelectLayout.setVerticalGroup(
            p_charSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_charSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_dummy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Velikost hracího pole");

        p_p1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tb_p1.setSelected(true);
        tb_p1.setText("Hráč 1");
        tb_p1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_p1ActionPerformed(evt);
            }
        });

        l_p1Char.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        l_p1Char.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_p1Char.setText("X");

        javax.swing.GroupLayout p_p1Layout = new javax.swing.GroupLayout(p_p1);
        p_p1.setLayout(p_p1Layout);
        p_p1Layout.setHorizontalGroup(
            p_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_p1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_p1Char, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_p1Layout.setVerticalGroup(
            p_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_p1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_p1Char, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        p_p2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tb_p2.setText("Hráč 2");
        tb_p2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_p2ActionPerformed(evt);
            }
        });

        l_p2Char.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        l_p2Char.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_p2Char.setText("Y");

        javax.swing.GroupLayout p_p2Layout = new javax.swing.GroupLayout(p_p2);
        p_p2.setLayout(p_p2Layout);
        p_p2Layout.setHorizontalGroup(
            p_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_p2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(l_p2Char, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_p2Layout.setVerticalGroup(
            p_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_p2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_p2Char, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        p_xSize.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Vodorovná velikost");

        s_xSize.setMajorTickSpacing(1);
        s_xSize.setMaximum(25);
        s_xSize.setMinimum(5);
        s_xSize.setPaintLabels(true);
        s_xSize.setPaintTicks(true);
        s_xSize.setSnapToTicks(true);
        s_xSize.setValue(8);

        javax.swing.GroupLayout p_xSizeLayout = new javax.swing.GroupLayout(p_xSize);
        p_xSize.setLayout(p_xSizeLayout);
        p_xSizeLayout.setHorizontalGroup(
            p_xSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_xSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_xSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(s_xSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        p_xSizeLayout.setVerticalGroup(
            p_xSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_xSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s_xSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_ySize.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Svislá velikost");

        s_ySize.setMajorTickSpacing(1);
        s_ySize.setMaximum(25);
        s_ySize.setMinimum(5);
        s_ySize.setPaintLabels(true);
        s_ySize.setPaintTicks(true);
        s_ySize.setSnapToTicks(true);
        s_ySize.setValue(8);

        javax.swing.GroupLayout p_ySizeLayout = new javax.swing.GroupLayout(p_ySize);
        p_ySize.setLayout(p_ySizeLayout);
        p_ySizeLayout.setHorizontalGroup(
            p_ySizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ySizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_ySizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                    .addComponent(s_ySize, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE))
                .addContainerGap())
        );
        p_ySizeLayout.setVerticalGroup(
            p_ySizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_ySizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s_ySize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Zpět");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_charSelect, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(p_p1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p_p2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addComponent(p_xSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_ySize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_charSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_xSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_ySize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tb_p1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_p1ActionPerformed
        if (tb_p2.isSelected() || (!tb_p1.isSelected() && !tb_p2.isSelected())) {
            tb_p1.setSelected(true);
            tb_p2.setSelected(false);
        }
    }//GEN-LAST:event_tb_p1ActionPerformed

    private void tb_p2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_p2ActionPerformed
        if (tb_p1.isSelected() || (!tb_p1.isSelected() && !tb_p2.isSelected())) {
            tb_p2.setSelected(true);
            tb_p1.setSelected(false);
        }
    }//GEN-LAST:event_tb_p2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_dummy;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel l_p1Char;
    private javax.swing.JLabel l_p2Char;
    private javax.swing.JPanel p_charSelect;
    private javax.swing.JPanel p_p1;
    private javax.swing.JPanel p_p2;
    private javax.swing.JPanel p_xSize;
    private javax.swing.JPanel p_xSize1;
    private javax.swing.JPanel p_ySize;
    private javax.swing.JSlider s_xSize;
    private javax.swing.JSlider s_xSize1;
    private javax.swing.JSlider s_ySize;
    private javax.swing.JToggleButton tb_p1;
    private javax.swing.JToggleButton tb_p2;
    // End of variables declaration//GEN-END:variables
}
